import React, { useState } from 'react';
import { Download, FileText, Image, Phone, Mail, Globe, CheckCircle, AlertTriangle } from 'lucide-react';
import { toast } from 'react-hot-toast';

const EvidencePacket = ({ incidentData, complaintId, onClose }) => {
  const [packetData, setPacketData] = useState({
    complaintId: complaintId || `NCRP-${Date.now()}`,
    incidentTitle: incidentData?.title || '',
    incidentDescription: incidentData?.description || '',
    location: incidentData?.location || '',
    pincode: incidentData?.pincode || '',
    timestamp: new Date().toISOString(),
    scammerDetails: incidentData?.scammerDetails || {},
    evidence: {
      screenshots: incidentData?.image ? [incidentData.image] : [],
      chatLogs: [],
      bankStatements: [],
      utrNumbers: [],
      additionalFiles: []
    }
  });

  const [additionalEvidence, setAdditionalEvidence] = useState({
    chatLogs: '',
    utrNumbers: '',
    bankStatements: '',
    additionalNotes: ''
  });

  const generatePacket = () => {
    const packet = {
      ...packetData,
      evidence: {
        ...packetData.evidence,
        chatLogs: additionalEvidence.chatLogs.split('\n').filter(log => log.trim()),
        utrNumbers: additionalEvidence.utrNumbers.split('\n').filter(utr => utr.trim()),
        bankStatements: additionalEvidence.bankStatements.split('\n').filter(stmt => stmt.trim()),
        additionalNotes: additionalEvidence.additionalNotes
      },
      documents: [
        'Government ID (Aadhaar/PAN)',
        'Bank statements',
        'Transaction screenshots',
        'Chat logs/screenshots',
        'Any other relevant documents'
      ],
      instructions: [
        'Take this packet to the nearest police station',
        'Present the NCRP complaint ID',
        'Request FIR registration',
        'Keep copies of all documents',
        'Follow up on case status regularly'
      ]
    };

    return packet;
  };

  const handleDownload = () => {
    const packet = generatePacket();
    
    // Create downloadable content
    const content = `
EVIDENCE PACKET FOR CYBERCRIME COMPLAINT
========================================

Complaint ID: ${packet.complaintId}
Generated: ${new Date(packet.timestamp).toLocaleString()}

INCIDENT DETAILS:
-----------------
Title: ${packet.incidentTitle}
Description: ${packet.incidentDescription}
Location: ${packet.location}
Pincode: ${packet.pincode}

SCAMMER DETAILS:
----------------
${packet.scammerDetails.name ? `Name: ${packet.scammerDetails.name}` : ''}
${packet.scammerDetails.phoneNumber ? `Phone: ${packet.scammerDetails.phoneNumber}` : ''}
${packet.scammerDetails.upiId ? `UPI ID: ${packet.scammerDetails.upiId}` : ''}
${packet.scammerDetails.email ? `Email: ${packet.scammerDetails.email}` : ''}
${packet.scammerDetails.website ? `Website: ${packet.scammerDetails.website}` : ''}
${packet.scammerDetails.scamType ? `Scam Type: ${packet.scammerDetails.scamType}` : ''}

EVIDENCE COLLECTED:
------------------
Screenshots: ${packet.evidence.screenshots.length} files
Chat Logs: ${packet.evidence.chatLogs.length} entries
UTR Numbers: ${packet.evidence.utrNumbers.length} entries
Bank Statements: ${packet.evidence.bankStatements.length} entries

DOCUMENTS TO CARRY:
------------------
${packet.documents.map(doc => `• ${doc}`).join('\n')}

INSTRUCTIONS:
------------
${packet.instructions.map(inst => `• ${inst}`).join('\n')}

Additional Notes:
${packet.evidence.additionalNotes || 'None'}

========================================
Generated by Prabhodhanyaya Incident Reporting System
    `;

    // Create and download file
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `evidence-packet-${packet.complaintId}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast.success('Evidence packet downloaded successfully!');
  };

  const handlePrint = () => {
    const packet = generatePacket();
    
    const printContent = `
      <html>
        <head>
          <title>Evidence Packet - ${packet.complaintId}</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 20px; }
            .header { background: #f0f0f0; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
            .section { margin-bottom: 20px; }
            .section h3 { color: #333; border-bottom: 2px solid #007bff; padding-bottom: 5px; }
            .evidence-item { background: #f9f9f9; padding: 10px; margin: 5px 0; border-radius: 4px; }
            .scammer-details { background: #fff3cd; padding: 15px; border-radius: 8px; }
            .instructions { background: #d1ecf1; padding: 15px; border-radius: 8px; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>🚨 EVIDENCE PACKET FOR CYBERCRIME COMPLAINT</h1>
            <p><strong>Complaint ID:</strong> ${packet.complaintId}</p>
            <p><strong>Generated:</strong> ${new Date(packet.timestamp).toLocaleString()}</p>
          </div>

          <div class="section">
            <h3>📋 INCIDENT DETAILS</h3>
            <div class="evidence-item">
              <p><strong>Title:</strong> ${packet.incidentTitle}</p>
              <p><strong>Description:</strong> ${packet.incidentDescription}</p>
              <p><strong>Location:</strong> ${packet.location}</p>
              <p><strong>Pincode:</strong> ${packet.pincode}</p>
            </div>
          </div>

          <div class="section">
            <h3>👤 SCAMMER DETAILS</h3>
            <div class="scammer-details">
              ${packet.scammerDetails.name ? `<p><strong>Name:</strong> ${packet.scammerDetails.name}</p>` : ''}
              ${packet.scammerDetails.phoneNumber ? `<p><strong>Phone:</strong> ${packet.scammerDetails.phoneNumber}</p>` : ''}
              ${packet.scammerDetails.upiId ? `<p><strong>UPI ID:</strong> ${packet.scammerDetails.upiId}</p>` : ''}
              ${packet.scammerDetails.email ? `<p><strong>Email:</strong> ${packet.scammerDetails.email}</p>` : ''}
              ${packet.scammerDetails.website ? `<p><strong>Website:</strong> ${packet.scammerDetails.website}</p>` : ''}
              ${packet.scammerDetails.scamType ? `<p><strong>Scam Type:</strong> ${packet.scammerDetails.scamType}</p>` : ''}
            </div>
          </div>

          <div class="section">
            <h3>📸 EVIDENCE COLLECTED</h3>
            <div class="evidence-item">
              <p><strong>Screenshots:</strong> ${packet.evidence.screenshots.length} files</p>
              <p><strong>Chat Logs:</strong> ${packet.evidence.chatLogs.length} entries</p>
              <p><strong>UTR Numbers:</strong> ${packet.evidence.utrNumbers.length} entries</p>
              <p><strong>Bank Statements:</strong> ${packet.evidence.bankStatements.length} entries</p>
            </div>
          </div>

          <div class="section">
            <h3>📄 DOCUMENTS TO CARRY</h3>
            <div class="evidence-item">
              ${packet.documents.map(doc => `<p>• ${doc}</p>`).join('')}
            </div>
          </div>

          <div class="section">
            <h3>📋 INSTRUCTIONS</h3>
            <div class="instructions">
              ${packet.instructions.map(inst => `<p>• ${inst}</p>`).join('')}
            </div>
          </div>

          ${packet.evidence.additionalNotes ? `
          <div class="section">
            <h3>📝 ADDITIONAL NOTES</h3>
            <div class="evidence-item">
              <p>${packet.evidence.additionalNotes}</p>
            </div>
          </div>
          ` : ''}

          <div style="margin-top: 30px; text-align: center; color: #666;">
            <p>Generated by Prabhodhanyaya Incident Reporting System</p>
          </div>
        </body>
      </html>
    `;

    const printWindow = window.open('', '_blank');
    printWindow.document.write(printContent);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-lg max-w-4xl w-full max-h-[90vh] overflow-y-auto">
        <div className="p-6">
          {/* Header */}
          <div className="flex justify-between items-center mb-6">
            <h2 className="text-2xl font-bold text-gray-900">
              📋 Evidence Packet Generator
            </h2>
            <button
              onClick={onClose}
              className="text-gray-500 hover:text-gray-700"
            >
              ✕
            </button>
          </div>

          {/* Incident Summary */}
          <div className="bg-blue-50 rounded-lg p-4 mb-6">
            <h3 className="text-lg font-semibold text-blue-900 mb-2">
              Incident Summary
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
              <div>
                <p><strong>Complaint ID:</strong> {packetData.complaintId}</p>
                <p><strong>Title:</strong> {packetData.incidentTitle}</p>
                <p><strong>Location:</strong> {packetData.location}</p>
              </div>
              <div>
                <p><strong>Generated:</strong> {new Date(packetData.timestamp).toLocaleString()}</p>
                <p><strong>Pincode:</strong> {packetData.pincode}</p>
              </div>
            </div>
          </div>

          {/* Scammer Details */}
          {packetData.scammerDetails && Object.keys(packetData.scammerDetails).length > 0 && (
            <div className="bg-yellow-50 rounded-lg p-4 mb-6">
              <h3 className="text-lg font-semibold text-yellow-900 mb-2">
                👤 Scammer Details
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
                {packetData.scammerDetails.name && (
                  <div className="flex items-center">
                    <FileText className="w-4 h-4 text-yellow-600 mr-2" />
                    <span><strong>Name:</strong> {packetData.scammerDetails.name}</span>
                  </div>
                )}
                {packetData.scammerDetails.phoneNumber && (
                  <div className="flex items-center">
                    <Phone className="w-4 h-4 text-yellow-600 mr-2" />
                    <span><strong>Phone:</strong> {packetData.scammerDetails.phoneNumber}</span>
                  </div>
                )}
                {packetData.scammerDetails.upiId && (
                  <div className="flex items-center">
                    <span><strong>UPI ID:</strong> {packetData.scammerDetails.upiId}</span>
                  </div>
                )}
                {packetData.scammerDetails.email && (
                  <div className="flex items-center">
                    <Mail className="w-4 h-4 text-yellow-600 mr-2" />
                    <span><strong>Email:</strong> {packetData.scammerDetails.email}</span>
                  </div>
                )}
                {packetData.scammerDetails.website && (
                  <div className="flex items-center">
                    <Globe className="w-4 h-4 text-yellow-600 mr-2" />
                    <span><strong>Website:</strong> {packetData.scammerDetails.website}</span>
                  </div>
                )}
                {packetData.scammerDetails.scamType && (
                  <div className="flex items-center">
                    <AlertTriangle className="w-4 h-4 text-yellow-600 mr-2" />
                    <span><strong>Scam Type:</strong> {packetData.scammerDetails.scamType}</span>
                  </div>
                )}
              </div>
            </div>
          )}

          {/* Additional Evidence */}
          <div className="bg-white border rounded-lg p-6 mb-6">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">
              📸 Additional Evidence
            </h3>
            
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Chat Logs/Screenshots
                </label>
                <textarea
                  rows="3"
                  value={additionalEvidence.chatLogs}
                  onChange={(e) => setAdditionalEvidence(prev => ({ ...prev, chatLogs: e.target.value }))}
                  placeholder="Paste chat logs or describe screenshots..."
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  UTR Numbers
                </label>
                <textarea
                  rows="2"
                  value={additionalEvidence.utrNumbers}
                  onChange={(e) => setAdditionalEvidence(prev => ({ ...prev, utrNumbers: e.target.value }))}
                  placeholder="Enter UTR numbers (one per line)..."
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Bank Statement Details
                </label>
                <textarea
                  rows="2"
                  value={additionalEvidence.bankStatements}
                  onChange={(e) => setAdditionalEvidence(prev => ({ ...prev, bankStatements: e.target.value }))}
                  placeholder="Describe bank statement details..."
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Additional Notes
                </label>
                <textarea
                  rows="3"
                  value={additionalEvidence.additionalNotes}
                  onChange={(e) => setAdditionalEvidence(prev => ({ ...prev, additionalNotes: e.target.value }))}
                  placeholder="Any additional information or evidence..."
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>
            </div>
          </div>

          {/* Documents Checklist */}
          <div className="bg-green-50 rounded-lg p-4 mb-6">
            <h3 className="text-lg font-semibold text-green-900 mb-2">
              📄 Documents to Carry
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
              {[
                'Government ID (Aadhaar/PAN)',
                'Bank statements',
                'Transaction screenshots',
                'Chat logs/screenshots',
                'Any other relevant documents'
              ].map((doc, index) => (
                <div key={index} className="flex items-center">
                  <CheckCircle className="w-4 h-4 text-green-600 mr-2" />
                  <span className="text-sm text-green-800">{doc}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Instructions */}
          <div className="bg-blue-50 rounded-lg p-4 mb-6">
            <h3 className="text-lg font-semibold text-blue-900 mb-2">
              📋 Instructions
            </h3>
            <div className="space-y-2">
              {[
                'Take this packet to the nearest police station',
                'Present the NCRP complaint ID',
                'Request FIR registration',
                'Keep copies of all documents',
                'Follow up on case status regularly'
              ].map((instruction, index) => (
                <div key={index} className="flex items-center">
                  <CheckCircle className="w-4 h-4 text-blue-600 mr-2" />
                  <span className="text-sm text-blue-800">{instruction}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex space-x-4">
            <button
              onClick={handleDownload}
              className="flex-1 bg-blue-600 text-white py-3 px-6 rounded-lg hover:bg-blue-700 transition-colors flex items-center justify-center"
            >
              <Download className="w-5 h-5 mr-2" />
              Download Evidence Packet
            </button>
            
            <button
              onClick={handlePrint}
              className="flex-1 bg-green-600 text-white py-3 px-6 rounded-lg hover:bg-green-700 transition-colors flex items-center justify-center"
            >
              <FileText className="w-5 h-5 mr-2" />
              Print Evidence Packet
            </button>
            
            <button
              onClick={onClose}
              className="px-6 py-3 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default EvidencePacket;
